-Fix actors items
DjLeChuck/foundryvtt-babele-translation-files-generator pull request #3
Opened 2024-03-09 23:57 UTC by Shadowheg

Bonjour, j'ai corrigé l'énumération des éléments dans les acteurs. Veuillez corriger d'autres champs personnalisés. J'aimerais pouvoir sélectionner des champs une seule fois, enregistrer les modifications en tant que modèle ou préréglage, et les utiliser lors de la récupération d'autres recueils.

2024-03-12 18:07 UTC, DjLeChuck requested changes
Hi,

Thank you for your PR. I can’t accept it, please have a look at my comments.

2024-03-12 18:07 UTC, DjLeChuck commented on scripts/exporters/actor-exporter.mjs
> +        'system.description.value', // Ensure you add fields relevant for your custom mapping here
This is a system specific value, it shouldn’t be hardcoded. Please remove it.

2024-03-12 18:07 UTC, DjLeChuck commented on scripts/exporters/abstract-exporter.mjs
> +  }
I don’t understand the aim of this change:
* If a piece of code is useless, remove it, no need to let it commented;
* You declare a `filename` variable but don’t use it;
* It seems you only move the code from `_getStringifiedDataset` to `_downloadFile`, am I right? Why this change?

2024-03-12 18:07 UTC, DjLeChuck commented on scripts/exporters/actor-exporter.mjs
> +      description: document.system && document.system.description ? document.system.description.value : "", // Check for existence
This is a system specific value, it shouldn’t be hardcoded. Please remove it.

2024-03-12 18:07 UTC, DjLeChuck commented on scripts/exporters/actor-exporter.mjs
> +          description: item.system && item.system.description ? item.system.description.value : "" // Check for existence
This is a system specific value, it shouldn’t be hardcoded. Please remove it.

2024-03-12 18:07 UTC, DjLeChuck commented on scripts/exporters/actor-exporter.mjs
> +                description: item.system.description.value // Ensure correct path based on your data structure
This is a system specific value, it shouldn’t be hardcoded. Please remove it.

2024-03-13 12:46 UTC, Shadowheg commented
Hi. Thanks for the reply. I have a question then - which Json path should I specify so that it uploads the description of each item type object? in pf2e system. Like this 
"id": JSON.actors8].items[]._id
"description":JSON.actors[].items[].system.description.value

Implying that it will upload every description for every item for every actor. 

My fix allows me to get what I want.

2024-03-15 20:40 UTC, closed without merging